language: node_js
node_js:
- node
dist: trusty
sudo: false
cache: yarn
script:
- echo "Deploy"
- yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT